### ISSUE TITLE
Error loading routes .xml

### ISSUE THREAD

**Issue by KRoover** [KillBait/AutoDrive_Course_Editor#59]
Whenever I try to open a route (via route manager or route file) I got an error "The route file XML could not be loaded".
On version 1.03 and prior it works as intended.
Console shows this.

[ERROR] 2023-02-20 09:55:04.950 [Main] AutoDriveEditor - For input string: "49.16"
java.lang.NumberFormatException: For input string: "49.16"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Long.parseLong(Long.java:711) ~[?:?]
        at java.lang.Long.parseLong(Long.java:836) ~[?:?]
        at AutoDriveEditor.XMLConfig.RouteManagerXML.loadRouteXML(RouteManagerXML.java:231) ~[AutoDriveEditor.jar:?]
        at AutoDriveEditor.XMLConfig.RouteManagerXML.loadRouteManagerXML(RouteManagerXML.java:51) ~[AutoDriveEditor.jar:?]
        at AutoDriveEditor.GUI.RoutesGUI.lambda$new$0(RoutesGUI.java:71) ~[AutoDriveEditor.jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) ~[?:?]
        at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
        at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
        at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
        at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
        at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) ~[?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]

**Comment by KillBait** [comment]
Thanks for the report, just confirmed it, i'm not 100% sure sure when i changed that piece of code.

Will be fixed in the next version, it should be out soon.
