### ISSUE TITLE
Issues trying to load overview.dds from Elmcreek 4x

### ISSUE THREAD

**Issue by HeroXx** [KillBait/AutoDrive_Course_Editor#81]
I am trying to generate an image for the 4x but I keep getting hit with this error when trying to do so:

```
[INFO ] 2024-09-25 16:05:28.610 [Main] GlobalExceptionHandler - Cannot load from int array because "rgbArray" is null
java.lang.NullPointerException: Cannot load from int array because "rgbArray" is null
        at java.awt.image.BufferedImage.setRGB(BufferedImage.java:1059) ~[?:?]
        at AutoDriveEditor.Managers.ImportManager.createBufferImageFromDDS(ImportManager.java:67) ~[AutoDriveEditor.jar:?]
        at AutoDriveEditor.Managers.ImportManager.importFromFS22(ImportManager.java:35) ~[AutoDriveEditor.jar:?]
        at AutoDriveEditor.GUI.Menus.MapImagesMenu.ImportFS22DDSMenu.actionPerformed(ImportFS22DDSMenu.java:55) ~[AutoDriveEditor.jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
        at javax.swing.AbstractButton.doClick(AbstractButton.java:374) ~[?:?]
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028) ~[?:?]
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072) ~[?:?]
        at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
        at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
        at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
        at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
        at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) ~[?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]

```

**Comment by HeroXx** [comment]
Map for reference:

https://www.kingmods.net/en/fs22/mods/17330/elm-creek-4x

**Comment by KillBait** [comment]
that's an odd error, i'll take a look at it as soon as i can

**Comment by KillBait** [comment]
It looks like the problem is an unsupported DDS format in the decoding code, i'll have to switch to something else for the next version, in the meantime i've attached the correct images, just drop it into the mapimages folder
[The_Elmcreek_Extension.zip](https://github.com/user-attachments/files/17149099/The_Elmcreek_Extension.zip)

**Comment by KillBait** [comment]
do you still have the log file from when you tried to convert that .dds file?, i just tried it now and worked fine, did you see this window pop up?
![DDS](https://github.com/user-attachments/assets/52c0c7f6-c928-4e66-9642-cf288a728208)

**Comment by HeroXx** [comment]
I didn’t get the OOM window but I can try bumping the memory to see if that helps?
