### ISSUE TITLE
Update for FS 25 and AD 3.x

### ISSUE THREAD

**Issue by ThaNeub** [KillBait/AutoDrive_Course_Editor#84]
Will there be an Update for the new FS 25 and Autodrive 3.x Version?

Until half an hour ago it worked perfectly, now it won´t load my config anymore, maybe because I set a few parking slots.

Log from console:

D:\Downloads\AutoDriveEditor_v1.0.8>java.exe -jar -Xms1024m -Xmx1024m .\AutoDriveEditor.Jar
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2024-12-29 17:35:12.595 [Main] AutoDriveEditor - Starting AutoDrive Editor v1.0.8 .....
[INFO ] 2024-12-29 17:35:12.598 [Main] AutoDriveEditor - Using Java Runtime Version 22
[INFO ] 2024-12-29 17:35:12.601 [Main] AutoDriveEditor - 'AutoDriveEditor_de_DE.properties' not found. looking in folders
[INFO ] 2024-12-29 17:35:12.601 [Main] AutoDriveEditor - No locale found at : ./AutoDriveEditor_de_DE.properties
[INFO ] 2024-12-29 17:35:12.601 [Main] AutoDriveEditor - No locale found at : ./locale/AutoDriveEditor_de_DE.properties
[INFO ] 2024-12-29 17:35:12.602 [Main] AutoDriveEditor - No locale found at : ./src/locale/AutoDriveEditor_de_DE.properties
[INFO ] 2024-12-29 17:35:12.602 [Main] AutoDriveEditor - No locale found at : ./src/main/resources/locale/AutoDriveEditor_de_DE.properties
[INFO ] 2024-12-29 17:35:12.602 [Main] AutoDriveEditor - Locale file not found..Using default locale en_US
[INFO ] 2024-12-29 17:35:12.719 [Main] AutoDriveEditor - Checking for <RecentFiles> key in EditorConfig.xml
[INFO ] 2024-12-29 17:35:12.720 [Main] AutoDriveEditor - Found <RecentFiles> tag
[INFO ] 2024-12-29 17:35:12.720 [Main] AutoDriveEditor - parsing 2 <Config> tags from XML
[INFO ] 2024-12-29 17:35:12.721 [Main] AutoDriveEditor - Checking for depreciated <mapzoomfactors> key in EditorConfig.xml
[INFO ] 2024-12-29 17:35:12.722 [Main] AutoDriveEditor - <mapzoomfactors> not found
[INFO ] 2024-12-29 17:35:12.722 [Main] AutoDriveEditor - parsing 2 known maps for editor use
[INFO ] 2024-12-29 17:35:12.722 [Main] AutoDriveEditor -   Checking <Zielonka> entry
[INFO ] 2024-12-29 17:35:12.723 [Main] AutoDriveEditor -   Checking <Riverbend_Springs> entry
[INFO ] 2024-12-29 17:35:12.724 [Main] AutoDriveEditor - Toolbar Location set to - Left
[INFO ] 2024-12-29 17:35:12.724 [Main] AutoDriveEditor - Initializing ButtonManager
[INFO ] 2024-12-29 17:35:12.764 [Main] AutoDriveEditor - Initializing CopyPaste Manager
[INFO ] 2024-12-29 17:35:12.764 [ConnectionDraw Thread] AutoDriveEditor - Starting ConnectionDraw Thread
[INFO ] 2024-12-29 17:35:12.765 [Main] AutoDriveEditor - Starting AutoSave Thread
[INFO ] 2024-12-29 17:35:12.764 [NodeDraw Thread] AutoDriveEditor - Starting NodeDraw thread
[INFO ] 2024-12-29 17:35:12.767 [Main] AutoDriveEditor - Started AutoSave Thread ( Interval in Minutes 10 , Max Slots 10 )
[INFO ] 2024-12-29 17:35:13.407 [Main] AutoDriveEditor - Connecting to GitHub for update check
[INFO ] 2024-12-29 17:35:14.119 [Main] AutoDriveEditor - No update available... Remote version 1.0.8 matches local version
[INFO ] 2024-12-29 17:35:19.410 [Main] AutoDriveEditor - config loadFile: D:\Eigene Dateien\Documents\My Games\FarmingSimulator2025\savegame3\AutoDrive_config.xml
[INFO ] 2024-12-29 17:35:19.428 [Main] AutoDriveEditor - ----------------------------
[INFO ] 2024-12-29 17:35:19.428 [Main] AutoDriveEditor - loadGameXMLFile Parsing D:\Eigene Dateien\Documents\My Games\FarmingSimulator2025\savegame3\AutoDrive_config.xml
[INFO ] 2024-12-29 17:35:19.430 [Main] AutoDriveEditor - Config was saved by AutoDrive '3.0.0.0'
[INFO ] 2024-12-29 17:35:19.430 [Main] AutoDriveEditor - ----------------------------
[INFO ] 2024-12-29 17:35:19.431 [Main] AutoDriveEditor - XML Root element : AutoDrive
[INFO ] 2024-12-29 17:35:19.431 [Main] AutoDriveEditor - Current Element <waypoints>
[INFO ] 2024-12-29 17:35:19.432 [Main] AutoDriveEditor - ----------------------------
[INFO ] 2024-12-29 17:35:19.432 [Main] AutoDriveEditor - Parsed 14644 <id> Entries
[INFO ] 2024-12-29 17:35:19.432 [Main] AutoDriveEditor - ## Checking all <id> entries for the correct numeric sequence
[INFO ] 2024-12-29 17:35:19.433 [Main] AutoDriveEditor - ## Finished checking all ID's for the correct sequence
[INFO ] 2024-12-29 17:35:19.434 [Main] AutoDriveEditor - Parsed 14644 <x> Entries
[INFO ] 2024-12-29 17:35:19.434 [Main] AutoDriveEditor - Parsed 14644 <y> Entries
[INFO ] 2024-12-29 17:35:19.436 [Main] AutoDriveEditor - Parsed 14644 <z> Entries
[INFO ] 2024-12-29 17:35:19.437 [Main] AutoDriveEditor - Parsed 14644 <out> Entries
[INFO ] 2024-12-29 17:35:19.439 [Main] AutoDriveEditor - Parsed 14644 <in> Entries
[INFO ] 2024-12-29 17:35:19.439 [Main] AutoDriveEditor - Parsed 14644 <flags> Entries
[INFO ] 2024-12-29 17:35:19.439 [Main] AutoDriveEditor - ----------------------------
[INFO ] 2024-12-29 17:35:19.440 [Main] AutoDriveEditor - Creating 14644 MapNodes
[INFO ] 2024-12-29 17:35:19.560 [Main] AutoDriveEditor - Finished creating all map nodes
[INFO ] 2024-12-29 17:35:19.561 [Main] AutoDriveEditor - Creating all incoming/outgoing connections
[INFO ] 2024-12-29 17:35:19.574 [Main] AutoDriveEditor - Created 24287 outgoing connections
[INFO ] 2024-12-29 17:35:19.584 [Main] AutoDriveEditor - Created 24265 incoming connections
[INFO ] 2024-12-29 17:35:19.585 [Main] AutoDriveEditor - ----------------------------
[INFO ] 2024-12-29 17:35:19.586 [Main] AutoDriveEditor - Load Parking Destinations - Parsing D:\Eigene Dateien\Documents\My Games\FarmingSimulator2025\savegame3\vehicles.xml
[ERROR] 2024-12-29 17:35:19.638 [Main] AutoDriveEditor - Cannot invoke "org.w3c.dom.Node.getNodeValue()" because the return value of "org.w3c.dom.NamedNodeMap.getNamedItem(String)" is null
java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Node.getNodeValue()" because the return value of "org.w3c.dom.NamedNodeMap.getNamedItem(String)" is null
        at AutoDriveEditor.XMLConfig.GameXML.loadVehiclesXMLParking(GameXML.java:724) ~[AutoDriveEditor.jar:?]
        at AutoDriveEditor.XMLConfig.GameXML.loadGameXMLFile(GameXML.java:359) ~[AutoDriveEditor.jar:?]
        at AutoDriveEditor.XMLConfig.GameXML.loadGameConfig(GameXML.java:71) ~[AutoDriveEditor.jar:?]
        at AutoDriveEditor.GUI.Menus.FileMenu.OpenConfigMenu.actionPerformed(OpenConfigMenu.java:51) ~[AutoDriveEditor.jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314) ~[?:?]
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407) ~[?:?]
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
        at javax.swing.AbstractButton.doClick(AbstractButton.java:374) ~[?:?]
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029) ~[?:?]
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073) ~[?:?]
        at java.awt.Component.processMouseEvent(Component.java:6621) ~[?:?]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3398) ~[?:?]
        at java.awt.Component.processEvent(Component.java:6386) ~[?:?]
        at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
        at java.awt.Component.dispatchEventImpl(Component.java:4996) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4828) ~[?:?]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
        at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
        at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
        at java.awt.Component.dispatchEvent(Component.java:4828) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:400) [?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:747) ~[?:?]
        at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:400) [?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) [?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) [?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]

**Comment by KillBait** [comment]
Is this only happening when editing FS25 configs?, is so, could you supply me the vehicles.xml file so i can take a look what has changed?

**Comment by ThaNeub** [comment]
It only happens with Editor Version 1.0.8
The Files are attached. (Zip with the configs and Logfile)

With Editor Version 1.0.6 I could open and edit the Course, strange.
[autoDriveEditor.log](https://github.com/user-attachments/files/18288031/autoDriveEditor.log)
[AD_Config.zip](https://github.com/user-attachments/files/18288032/AD_Config.zip)

**Comment by KillBait** [comment]
V1.06 works as it doesn't have support for the parking spots, looking at the config you supplied it appears FS25 has changed the way it stores the vehicle id and AD has changed the way it stores the parking spot information, so that explains the crash, i'll look into fixing this and get a new version out ASAP.

**Comment by ThaNeub** [comment]
Thank you!

**Comment by zachary-wang12** [comment]
@KillBait 
Thanks for your great job bro. BTW, Is there any plan to support FS25? Current verison cannot determine map file.

**Comment by KillBait** [comment]
New version is out (v1.0.9) and should fix the crash related to FS25

**Comment by KillBait** [comment]
> @KillBait Thanks for your great job bro. BTW, Is there any plan to support FS25? Current verison cannot determine map file.

The editor is 95% AD/FS agnostic, the only reason it detects the version numbers is to make changes when loading/saving configs
